routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

// Route::put('tickets/{ticket}/updateRequest', 'TicketController@resourceRequestUpdate');
Route::delete('resource_categories/deleteAll', 'ResourceCategoryController@deleteAll')->name('resource_categories.deleteAll');

Route::delete('/temp/clear','TempController@clearTemp')->name('temp.clear');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('si_resource', 'SIResourcesController');
Route::resource('temp','TempController');
Route::resource('resource_categories', 'ResourceCategoryController');
Route::resource('projects', 'ProjectController');
Route::resource('tickets','TicketController');

app/Http/Controllers/TempController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\SI_resources;
use Str;
use Session;
use App\Project;

class TempController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('notGuest');

        $projects = Project::all();
        $resources = [];
        if(Session::has('temp')){
            $resource_ids = array_keys(Session::get('temp'));
            // dd($resource);

            $resources = SI_resources::find($resource_ids);
            foreach ($resources as $resource) {
                $resource['quantity'] = Session::get("temp.$resource->id");
            }

            return view('temp.index',[
                'si_resources' => $resources,
                'projects' => $projects
            ]);
        }

        
        return view('temp.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('notGuest');

        $resources = SI_resources::all();
        $inputs = $request->all();
        // dd($inputs);
        
        // for each inputs if the check box value is on then check in their name(id) is equals to quantity id
        // dd($inputs);
        foreach ($inputs as $input => $value) {
            if($value == 'on'){
                foreach($inputs as $quantityName => $quantityValue){
                    if("quantity".$input == $quantityName){
                        echo $quantityName ." = " .$quantityValue;

                        $request->validate([
                            $quantityName => 'required|numeric|min:1'
                        ]);

                        $request->session()->put("temp.$input",$quantityValue);
                    }
                }
            }
        }

                        // dd(Session::get('temp'));

                        return redirect(route('temp.index'));


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->authorize('notGuest', $id);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('notGuest', $id);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('notGuest', $id);

        $request->validate([
         'id' => 'required',
         'quantity' => 'required|numeric|min:1'
      ]);


        //get the request input
       $item_quantity = $request->input('quantity');
       $id = $request->input('id');

        //set entry to be pass to session
        // $add_to_cart = [$id => $product_quantity];
        // store to session
        // $request->session()->put("cart",[$add_to_cart]);
       $request->session()->put("temp.$id",$item_quantity);
       return redirect(route('temp.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('notGuest', $id);

        Session::forget("temp.$id");

       return redirect(route('temp.index'));
    }

    public function clearTemp()
    {
        $this->authorize('notGuest', $id);
        
       Session::forget("temp");
       // echo "Empty Cart Button is Clicked";
       return redirect(route('temp.index'));
    }
}

resources/views/temp/index.blade.php
@extends('layouts.app')

{{-- {{dd($si_resources)}} --}}
@section('content')
<section class="container">
	<div class="row">
		<div class="col-12 col-md-10 mx-auto">
			<h1 class="text-center">Requested Resources</h1>
			@if (Session::has('temp') && count(Session::get('temp')))
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>

						<tr>
							<th>Name</th>
							<th>Resource ID</th>
							<th>Control Number</th>
							<th>Quantity</th>
							<th colspan="3">Details</th>
							{{-- <th></th> --}}
						</tr>

					</thead>
					<tbody>

						{{-- expr --}}
						@foreach ($si_resources as $resource)
						{{-- expr --}}

						<tr>
							<td>{{$resource->name}}</td>
							<td>{{$resource->id}}</td>
							<td>{{$resource->control_number}}</td>
							<td>
								<form method="POST" id="updateForm{{$resource->id}}" action="{{route('temp.update', ['temp'=>$resource->id])}}">
									@csrf
									@method('PUT')
									<input type="hidden" name="id" value="{{$resource->id}}">
									<div class="form-group">
										<div class="input-group">

											<input type="number" name="quantity" data-id="{{$resource->id}}"value="{{$resource->quantity}}" class="form-control">
											<div class="input-group-append">
												<button class="btn btn-secondary" type="submit" form="updateForm{{$resource->id}}" data-id="{{$resource->id}}">Update</button>
											</div>
										</div>
									</div>
								</form>
							</td>
							<td><button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#a{{$resource->id}}">View Details</button></td>
							<td>
								<form action="{{route('temp.destroy',[ 'temp' => $resource->id])}}" method="POST">
									@csrf
									@method('DELETE')
									<button class="btn btn-outline-danger">Cancel</button>
								</form>
							</td>
						</tr>

						@endforeach

					</tbody>

					<tfoot>
						<tr>
							<th>
								@can('isManager')
									Select Project
								@endcan
							</th>
							<form method="POST" action="{{route('tickets.store')}}">
								<td colspan="2">
									@can('isManager')

										<select class="form-control" name="project">
											@foreach ($projects as $project)
											<option value="{{$project->id}}">{{$project->name}}</option>
											@endforeach
										</select>

									@endcan
									@can('isEmployee')
										<input type="hidden" name="project" value="{{ Auth::user()->project_id }}">
									@endcan
								</td>
								<td></td>
								<td>
									@csrf
									<button class="btn btn-success">Confirm Request</button>
								</td>
							</form>
							<td>
								<form  action="{{route('temp.clear')}}" method="POST">
									@csrf
									@method('DELETE')
									<button class="btn btn-danger btn-block">Cancel Requests</button>
								</form>
							</td>

						</tr>
					</tfoot>


				</table>

			</div>

		</div>

	</div>


</section>


@foreach ($si_resources as $resource)
<!-- Modal -->
<div class="modal fade" id="a{{$resource->id}}" tabindex="-1" role="dialog" aria-labelledby="label{{$resource->id}}" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="label{{$resource->id}}">{{$resource->name}}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<section class="modal-body">
				<div class="row">

					<div class="col-12 col-md-8 mx-auto">


						<div class="card">
							<img src="{{url('/public/'.$resource->images)}}" class="card-img-top img-fluid">
							<div class="card-body">

								<h2 class="card-title">{{$resource->name}}</h2>
								<p class="card-text">
									<strong>No. of Stocks: </strong>{{$resource->stocks}}
								</p>
								<p class="card-text">
									<strong>Details: </strong>{{$resource->details}}
								</p>
							</div>
							<div class="card-footer">

								{{-- @can('isAdmin') --}}
								{{-- edit button --}}

								{{-- delete button --}}
								{{-- <form method="POST"class="my-2" action="{{route('si_resource.destroy',['si_resource' => $resource->id])}}">
									@csrf
									@method('DELETE')
									<button class="btn btn-warning btn-block">Delete Resource</button>
								</form> --}}
								{{-- @endcan --}}
							</div>


						</div>

					</div>

				</div>

			</section>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Request</button>
			</div>
		</div>
	</div>
</div> {{-- end modal --}}

@endforeach

@else
	<div class="alert alert-warning">
		<h3 class="text-center">You have no request</h3>
	</div>
	<a href="{{route('si_resource.index')}}" class="btn btn-info btn-block">Request a Resource</a>

@endif

@endsection