routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

// Route::put('tickets/{ticket}/updateRequest', 'TicketController@resourceRequestUpdate');
Route::delete('resource_categories/deleteAll', 'ResourceCategoryController@deleteAll')->name('resource_categories.deleteAll');

Route::delete('/temp/clear','TempController@clearTemp')->name('temp.clear');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('si_resource', 'SIResourcesController');
Route::resource('temp','TempController');
Route::resource('resource_categories', 'ResourceCategoryController');
Route::resource('projects', 'ProjectController');
Route::resource('tickets','TicketController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
// use App\User;

class Project extends Model
{
    use SoftDeletes;
    public function user(){
    	return $this->belongsTo('App\User');
    	// return 'waw';
    }

    public function projectManager(){
        return $this->belongsTo('App\User');
    }

    public function employee(){
        return $this->hasMany('App\User');
    }

    public function projectStatus(){
    	return $this->belongsTo('App\ProjectStatus');
    }

    public function tickets(){
    	return $this->hasMany('App\Tickets');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;
use App\User;
use Str;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Project $project)
    {
        $this->authorize('notGuest', $project);

        $projects = Project::all();
        $users = User::all();
        return view('projects.index',[

            'projects' => $projects,
            'users' => $users
            
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Project $project)
    {
        $this->authorize('notGuest', $project);
        $this->authorize('create', $project);
        $managers = User::where('role_id', 3)->get();
        // dd($managers);
        return view('projects.create')->with('managers',$managers);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Project $project)
    {
        // dd($random_char);
      $this->authorize('isAdmin', $project);
      $this->authorize('notGuest', $project);

        
        echo "andito ka";
        $request->validate([
            'name' => 'required',
            'details' => 'required',
            'projectManager' => 'required'
        ]);

        $data = $request->all();
        extract($data);

        $firstLetters = [];

        $newName = explode(" ",$name);
        
        $nameStr = $newName[0];

        // newName is an array of names
        // get the length of newName if the length is greaterthan 1
        // take the first letters of each names starting from index 1

        if (count($newName) > 1) {
            
            for ($i=1; $i < count($newName); $i++) { 
                 
                $names = $newName[$i];
                array_push($firstLetters, $names[0]);
            }
        }

        $firstLetters = implode("",$firstLetters);
        // dd($firstLetters);

        $nameStr = strtoupper($nameStr);
        $firstLetters = strtoupper($firstLetters);

        $random_char = strtoupper(Str::random(2));


        $project = new Project;
        $project->name = $name;
        $project->project_code = $nameStr.$firstLetters.$random_char."_".date('Ymd');
        $project->details = $details;
        $project->project_manager_id = $projectManager;
        $project->save();

        $request->session()->flash('createProjectSuccess','Successfully Added A Project');
        return redirect(route('projects.show',['project' => $project->id]));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        $this->authorize('isAdmin', $project);
        $users = User::where('role_id',3)->get();
        return view('projects.show',[
            'project' => $project,
            'users' => $users
        ]);


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $this->authorize('isAdmin', $project);

        $users = User::where('role_id',3)->get();
        return view('projects.edit',
            [
                'project'=>$project,
                'users' => $users
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        $this->authorize('isAdmin', $project);

        $request->validate([
            'name' => 'required',
            'details' => 'required',
            'projectManager' => 'required'
        ]);

        $data = $request->all();
        extract($data);

        if ($project->name == $name && $project->details == $details
            && $project->project_manager_id == $projectManager) {
            $request->session()->flash('update_failed','No changes made');
            return redirect(route('projects.show',['product'=> $product->id]));
        }
        else
        {


            $firstLetters = [];

            $newName = explode(" ",$name);
            
            $nameStr = $newName[0];

            // newName is an array of names
            // get the length of newName if the length is greaterthan 1
            // take the first letters of each names starting from index 1

            if (count($newName) > 1) {
                
                for ($i=1; $i < count($newName); $i++) { 
                     
                    $names = $newName[$i];
                    array_push($firstLetters, $names[0]);
                }
            }

            $firstLetters = implode("",$firstLetters);
            // dd($firstLetters);

            $nameStr = strtoupper($nameStr);
            $firstLetters = strtoupper($firstLetters);

            $random_char = strtoupper(Str::random(2));

            $project->name = $name;
            $project->details = $details;
            $project->project_manager_id = $projectManager;
            $project->save();

            $request->session()->flash('updateProjectSuccess','Project Successfully Updated');
            return redirect(route('projects.show',['project' => $project->id]));

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $this->authorize('isAdmin', $project);
        
        $project->delete();

        return redirect(route('projects.index'))->with('destroy_message', 'Project Deleted');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
	
	<section class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h1>Start A project</h1>
				<form method="POST" action="{{route('projects.store')}}">
					@csrf
					<div class="form-group">
						
						<label class="form-control-label" for="name">Name:</label>
						<input class="form-control" type="text" name="name" placeholder="Project Name" id="name">		
						
					</div>
					<div class="form-group">
						<label class="form-control-label" for="details">Details</label>
						<textarea class="form-control" id="details" name="details" placeholder="Enter Details"></textarea>
					</div>
					<div class="form-group">
						<label class="form-control-label" for="projectManager">Select Project Manager</label>
						<select class="form-control" id="projectManager" name="projectManager">
							@foreach ($managers as $manager)
								{{-- expr --}}
								<option value="{{$manager->id}}">{{$manager->name}}</option>
							@endforeach
						</select>
					</div>
					<button class="btn btn-primary btn-block">Submit</button>
				</form>				
			</div>
		</div>	
		
	</section>

@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')

<section class="container">
	<div class="row">

		<div class="col-12 col-md-8 mx-auto">
			<h2 class="text-center">Edit Project</h2>
			<form method="POST" id="updateForm" action="{{route('projects.update',['project' => $project->id])}}">
				@csrf
				@method('PUT')
				<div class="form-group">

					<label class="form-control-label" for="name">Name:</label>
					<input class="form-control" type="text" name="name" placeholder="Project Name" id="name" value="{{$project->name}}">		

				</div>
				<div class="form-group">
					<label class="form-control-label" for="details">Details</label>
					<textarea class="form-control" id="details" name="details" placeholder="Enter Details">{{$project->details}}</textarea>
				</div>
				<div class="form-group">
					<label class="form-control-label" for="projectManager">Select Project Manager</label>
					<select class="form-control" id="projectManager" name="projectManager">
						@foreach ($users as $user)

						<option value="{{$user->id}}"
							{{$user->id == $project->project_manager_id? 'selected' : ''}}
							>{{$user->name}}</option>
						}
						@endforeach
					</select>
				</div>

				<button class="btn btn-primary btn-block">Update</button>

			</form>

		</div>
	</section>


	@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')


@section('content')

	<section class="container">
		<div class="row">
			<div class="col-10 m-auto">
				<h1 class="d-inline-block">Projects</h1>
				@can('isAdmin')
					<a class="btn btn-link text-right" href="{{ route('projects.create') }}">create</a>
				@endcan
				<div class="table-responsive">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th>Project Name:</th>
								<th>Project Code:</th>
								<th>Project Manager:</th>
								<th>Project Status:</th>
								<th>Project Details</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($projects as $project)
								{{-- expr --}}
								<tr>
									<td>{{$project->name}}</td>
									<td>{{$project->project_code}}</td>
									<td>{{$project->projectManager->name}}</td>
									<td>{{$project->projectStatus->name}}</td>
									<td><button class="btn btn-primary btn-block" data-toggle="modal" data-target="#descModal">View Details</button></td>
								</tr>
							@endforeach
						</tbody>
						
					</table>
					
				</div>
				
			</div>
			
		</div>
		
	</section>

	@foreach ($projects as $project)

		<!-- Modal -->
		<div class="modal fade" id="descModal" tabindex="-1" role="dialog" aria-labelledby="descModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="descModalLabel">Details</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<section class="modal-body">
						<div class="row">

							<div class="col-12 col-md-8 mx-auto">

								<p>{{$project->details}}</p>

								@can('isAdmin')
								    {{-- expr --}}
									<a href="{{route('projects.edit',['project' => $project->id])}}" class="btn btn-warning btn-block my-2">Edit</a>

									<form method="POST" action="{{route('projects.destroy',['project' => $project->id])}}">
										
										@csrf
										@method('DELETE')
										<button class="btn btn-danger btn-block">Delete</button>

									</form>

								@endcan
								
							</div>

						</div>

					</section>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					</div>
				</div>
			</div>
		</div> {{-- end modal --}}
	@endforeach
	
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')

							{{-- {{dd($project->manager)}} --}}
{{-- {{dd($project->manager->name)}} --}}

<section class="container">
	<div class="row">
		<div class="col-12 col-md-8 m-auto">

			<div class="card">

				<div class="card-body">

					<h2 class="card-title">{{$project->name}}</h2>
					<p class="card-text">
						<strong>Project Code: </strong>{{$project->project_code}}
					</p>
					<p class="card-text">
						<strong>Project Manager: </strong>
						@foreach ($users as $user)
							@if ( $user->id == $project->project_manager_id)
								{{$user->name}}
							@endif
						@endforeach
					</p>
					<p class="card-text">
						<strong>Details: </strong>{{$project->details}}
					</p>
					<p class="card-text">
						<strong>Status: </strong><span class="badge badge-info">{{$project->projectStatus->name}}</span>
					</p>
				</div>
				<div class="card-footer">

					{{-- view button --}}
					<a href="{{route('projects.index')}}" class="btn btn-primary btn-block">View All Projects</a>

					{{-- @can('isAdmin') --}}
					{{-- edit button --}}
					{{-- <a class="btn btn-info btn-block" href="{{route('projects.edit',['project'=> $project->id])}}">Edit Project</a> --}}
					<button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#updateModal">Edit Project</button>

					{{-- delete button --}}
					<form method="POST"class="my-2" action="{{route('projects.destroy',['project' => $project->id])}}">
						@csrf
						@method('DELETE')
						<button class="btn btn-warning btn-block">Delete Project</button>
					</form>
					{{-- @endcan --}}
				</div>


			</div>

		</div>
	</div>

</section>
<!-- Modal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="updateLabel">Edit Project</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<section class="modal-body">
				<div class="row">

					<div class="col-12 col-md-8 mx-auto">
						<h2>{{$project->name}}</h2>
						<form method="POST" id="updateForm" action="{{route('projects.update',['project' => $project->id])}}">
							@csrf
							@method('PUT')
							<div class="form-group">

								<label class="form-control-label" for="name">Name:</label>
								<input class="form-control" type="text" name="name" placeholder="Project Name" id="name" value="{{$project->name}}">		

							</div>
							<div class="form-group">
								<label class="form-control-label" for="details">Details</label>
								<textarea class="form-control" id="details" name="details" placeholder="Enter Details">{{$project->details}}</textarea>
							</div>
							<div class="form-group">
								<label class="form-control-label" for="projectManager">Select Project Manager</label>
								<select class="form-control" id="projectManager" name="projectManager">
									@foreach ($users as $user)

										<option value="{{$user->id}}"
											{{$user->id == $project->project_manager_id? 'selected' : ''}}
											>{{$user->name}}</option>
											}
									@endforeach
								</select>
							</div>

						</form>
						
					</div>

				</div>

			</section>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="submit" form="updateForm" class="btn btn-primary">Submit</button>
			</div>
		</div>
	</div>
</div> {{-- end modal --}}



@endsection