routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

// Route::put('tickets/{ticket}/updateRequest', 'TicketController@resourceRequestUpdate');
Route::delete('resource_categories/deleteAll', 'ResourceCategoryController@deleteAll')->name('resource_categories.deleteAll');

Route::delete('/temp/clear','TempController@clearTemp')->name('temp.clear');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('si_resource', 'SIResourcesController');
Route::resource('temp','TempController');
Route::resource('resource_categories', 'ResourceCategoryController');
Route::resource('projects', 'ProjectController');
Route::resource('tickets','TicketController');

app/SI_resources.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SI_resources extends Model
{
    public function category(){
    	return $this->belongsTo('App\ResourceCategory');
    }

    // public function tickets(){
    // 	return $this->belongsToMany('App\Ticket');
    // }

    protected $fillable = ['name', 'details', 'category_id', 'images'];
}

app/Http/Controllers/SIResourcesController.php
<?php

namespace App\Http\Controllers;

use App\SI_resources;
use Illuminate\Http\Request;
use Str;
use App\ResourceCategory;

class SIResourcesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(SI_resources $si_resource)
    {   
        $this->authorize('notGuest', $si_resource);
        
        $si_resources = SI_resources::all();
        return view('SI_resources.index',[
            'si_resource' => $si_resources 
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(SI_resources $si_resource)
    {
        $this->authorize('create', $si_resource);

        $categories = ResourceCategory::all();
        return view('SI_resources.create')->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, SI_resources $si_resource)
    {

        $this->authorize('create', $si_resource);

        $request->validate([
            'name' => 'required',
            'details' => 'required',
            'image'=> 'required|image|max:3000',
            'stocks' => 'required'
        ]);

        // echo "Hello World";

        $file = $request->file('image');


        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

        $file_extension = $file->extension();

        $random_chars = Str::random(10);
        $random_char2 = Str::random(2);

        $regex = "/[\-\ \_]/";
        $fileNameLetters = [];

        if (count_chars($file_name) > 7) {
            if(preg_match($regex, $file_name)){
                $file_nameArr = preg_split($regex, $file_name);
                // dd($file_nameArr);

                for ($i=0; $i < count($file_nameArr); $i++) { 
                    $fileName = $file_nameArr[$i];
                    // dd($fileName);
                    empty($fileName)? "" : array_push($fileNameLetters, $fileName[0]);
                    // dd($fileNameLetters);
                }
                
                $file_name = implode("", $fileNameLetters);
                $new_file_name = date('Y-m-d-H-i-s')."_".$random_chars."_".$file_name.".".$file_extension;
                // dd($new_file_name);

                
            }
            else
            {
                for ($i=0; $i <= 7 ; $i++) { 
                    array_push($fileNameLetters, $fileName[$i]);
                }
                $file_name = implode("", $fileNameLetters);
                $new_file_name = date('Y-m-d-H-i-s')."_".$random_chars."_".$file_name.".".$file_extension;


            }

        } else{

            $new_file_name = date('Y-m-d-H-i-s')."_".$random_chars."_".$file_name.".".$file_extension;
        }



        $filepath = $file->storeAs('images',$new_file_name,'public');

        $data = $request->all(
            'name',
            'category',
            'details',
            'stocks'
        );

        extract($data);
        $newName = explode(" ",$name);
        $newName = implode("_",$newName);

        if ($category == 1) {
            $controlNumber = $newName."_".$random_char2."_".date('Ymd');
        }else{
            $controlNumber = $newName."_".date('Ymd');
        }

        $resources = new SI_resources;
        $resources->name = $name;
        $resources->category_id = $category;
        $resources->details = $details;
        $resources->images = $filepath;
        $resources->control_number = $controlNumber;
        $resources->stocks = $stocks;
        $resources->save();

        return redirect(route('si_resource.show',['si_resource'=> $resources->id]));
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\SI_resources  $sI_resources
     * @return \Illuminate\Http\Response
     */
    public function show(SI_resources $si_resource)
    {
        // dd($sI_resources);
        // echo "hallooo!!";
        $this->authorize('create', $si_resource);

        return view('SI_resources.show')->with('si_resource', $si_resource);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SI_resources  $sI_resources
     * @return \Illuminate\Http\Response
     */
    public function edit(SI_resources $si_resource)
    {
        $this->authorize('update', $si_resource);

        $categories = ResourceCategory::all();
        return view('SI_resources.create',[
            'si_resource' => $si_resource,
            'categories' => $categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SI_resources  $sI_resources
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SI_resources $si_resource)
    {
        $this->authorize('update', $si_resource);

        // dd($request->input('details'));

        $request->validate([
            'name'=>'required|string',
            // 'image'=> 'required|image|max:3000',
            'details' => 'required|string'

        ]);

        // 2. update database if there are differences between the details from form and the current details of the product;
        if (!$request->hasFile('image') &&
            $si_resource->name == $request->input('name') &&
            $si_resource->details == $request->input('details')&&
            $si_resource->category_id == $request->input('category')) {
            $request->session()->flash('update_failed','No changes made');
        return redirect(route('si_resource.edit',['si_resource'=> $si_resource->id]));
    }else{

            // update the entry in the database and return the update entry

            //check if there's a file uploaded
     if($request->hasFile('image')){
       $request->validate([
         'image' => 'required|image|max:3000'
     ]);
       $file = $request->file('image');
       $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
       $file_extension = $file->extension();
       $random_chars = Str::random(10);
       $new_file_name = date('Y-m-d-H-i-s')."_".$random_chars."_".$file_name.".".$file_extension;
       $filepath = $file->storeAs('images',$new_file_name,'public');

       $si_resource->images=$filepath;
   }

                // $product = new Product;
   $si_resource->name = $request->input('name');
   $si_resource->category_id = $request->input('category');
   $si_resource->details = $request->input('details');
   $si_resource->save();

   $request->session()->flash('update_success', 'Product successfully updated');

   return redirect(route('si_resource.show',['si_resource'=> $si_resource->id]));
}
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SI_resources  $sI_resources
     * @return \Illuminate\Http\Response
     */
    public function destroy(SI_resources $si_resource)
    {
        $this->authorize('delete', $si_resource);

        // echo "dapat mawawala to";
        $si_resource->delete();

        // $request->session()->flash('delete_success', 'Product successfully deleted');
        return redirect(route('si_resource.index'))->with('destroy_message','Resource Successfully Deleted');
    }
    
}

resources/views/SI_resources/create.blade.php
@extends('layouts.app')

@section('content')

	<section class="container">
		<div class="row">
			<div class="col-12 col-md-8 m-auto">
				@if (Session::has('update_failed'))
					<div class="alert alert-warning">
						{{Session::get('update_failed')}}
					</div>
				@endif
				@if ($errors->any() && !$errors->has('add-category'))
					@foreach($errors->all() as $error)
						<div class="alert alert-danger">
							<small>{{$error}}</small>
						</div>
					@endforeach
				@endif

				<h1>{{isset($si_resource)? "Edit Resource" : "Add Resource"}}</h1>
				<form method="POST" enctype="multipart/form-data" action="
					@if (isset($si_resource))
						{{route('si_resource.update',['si_resource' => $si_resource->id])}}
					@else
						{{route('si_resource.store')}}
					@endif">

					@csrf
					@if (isset($si_resource))
						@method('PUT')
					@endif
					<div class="form-group">
						<label for="name">Name:</label>
						<input type="text" name="name" id="name" class="form-control" value="{{isset($si_resource)? $si_resource->name : ""}}"
						required="">
					</div>
					<div class="form-group">
						<label for="category">Category:</label>
						<select class="form-control" id="category" name="category">
							@foreach ($categories as $category)
								
								{{-- options --}}
								<option value="{{$category->id}}"
									@if (isset($si_resource))
										@if($category->id == $si_resource->id)
											selected
										@endif
									@endif	
								>{{$category->name}}</option>
								{{-- end of options --}}

							@endforeach
						</select>
					</div>

					<div class="form-group">
						<label for="stocks">Stocks:</label>
						<input type="number" name="stocks" id="stocks" placeholder="input number of stocks" class="form-control" value="{{isset($si_resource)? $si_resource->stocks : ""}}">
					</div>

					<div class="form-group">
						<label for="details">Details:</label>
						<textarea name="details" id="details" class="form-control">{{
							isset($si_resource)? $si_resource->details : ""
						}}</textarea>
					</div>
					<div class="form-group">
						<label for="image">Image:</label>
						<input type="file" name="image" id="image" class="form-control-file">
					</div>
					<button class="btn btn-primary btn-block">{{!isset($si_resource)? "Add Resource": "Edit Resource"}}</button>
				</form>

			</div>
			<div class="col-12 col-md-3">
				@if (Session::has('category_message'))
					<div class="alert alert-success">
						<small>{{Session::get('category_message')}}</small>
					</div>
				@endif
				@if ($errors->has('add-category'))
					<div class="alert alert-danger">
						<small>Category Not Added</small>
					</div>
				@endif
				<form method="POST" action="{{route('resource_categories.store')}}">
					@csrf
					<div class="form-group mx-auto text-center">
						<h3>Add Category</h3>
						
						<input class="form-control" type="text" name="add-category" id="add-category" placeholder="Add Category">
						<button class="btn btn-secondary btn-block">Submit</button>
					</div>
				</form>
				
			</div>
		</div>
		
	</section>
@endsection

resources/views/SI_resources/index.blade.php
@extends('layouts.app')

@section('content')
<section class="container">
	<div class="row">
		<div class="col-12 col-md-10 mx-auto">
					
			<div class="table-responsive">
				<h1 class="text-center">Resources
					@can('isAdmin')
						<a href="{{route('si_resource.create')}}" class="btn btn-outline-info">Add Resource</a>
					@endcan


				</h1>

				<table class="table table-hover table-striped table-primary rounded">
					<thead>
						<tr class="text-center">
							<th>Name</th>
							<th>Resource ID</th>
							<th>{{strtolower(Auth::user()->role->name) == 'employee'? 'Quantity' : 'Control Number'}}</th>
							<th>No. of Stocks</th>
							<th>Details</th>
							<th>
								<div class="form-check form-group">
									<input class="form-check-input" type="checkbox" name="selectAll" id="selectAll" onclick="toggle(this)"> 
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						<form id="checkboxForm" method="POST" action="{{route('temp.store')}}">
							@foreach ($si_resource as $resource)
							{{-- expr --}}
							@csrf
							<tr class="text-center">
								<th>{{$resource->name}}</th>
								<td>{{$resource->id}}</td>
								<td>
									@if (strtolower(Auth::user()->role->name) == 'employee')
										{{-- expr --}}
									<div class="form-group">
										<div class="input-group mb-3">
											{{-- <div class="input-group-prepend">
												<button class="btn btn-outline-secondary deduct-qty" type="button" data-id="{{$resource->id}}">-</button>
											</div> --}}
											<input type="text" class="form-control input-quantity" name="quantity{{$resource->id}}"value="1" min="1"  data-id="{{$resource->id}}">
											{{-- <div class="input-group-append">
												<button class="btn btn-outline-secondary add-qty" type="button"  data-id="{{$resource->id}}">+</button>
											</div> --}}
										</div>
									</div>
									@else
										{{$resource->control_number}}
									@endif
								</td>
								<td>{{$resource->stocks}}</td>
								<td>
									<button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#a{{$resource->id}}">View Details</button>
								</td>
								<td>
									<input type="checkbox" name="{{$resource->id}}">
								</td>
								
							</tr>

							@endforeach
						</form>
					</tbody>
					<tfoot class="table-light">
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>

							<td>
								
							</td>
							
							    {{-- expr --}}
								<td>
									@cannot('isAdmin')
										<button class="btn btn-primary" type="submit" form="checkboxForm">Request</button>
									@endcannot
								</td>
						</tr>

					</tfoot>

				</table>

			</div>

		</div>
	</div>

</section>


@foreach ($si_resource as $resource)
<!-- Modal -->
<div class="modal fade" id="a{{$resource->id}}" tabindex="-1" role="dialog" aria-labelledby="label{{$resource->id}}" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="label{{$resource->id}}">Details</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<section class="modal-body">
				<div class="row">

					<div class="col-12 col-md-8 mx-auto">


						<div class="card">
							<img src="{{url('/public/'.$resource->images)}}" class="card-img-top img-fluid">
							<div class="card-body">

								<h2 class="card-title">{{$resource->name}}</h2>
								<p class="card-text">
									<strong>No. of Stocks: </strong>{{$resource->stocks}}
								</p>
								<p class="card-text">
									<strong>Details: </strong>{{$resource->details}}
								</p>
							</div>

							@can('isAdmin')
								<div class="card-footer">

									{{-- @can('isAdmin') --}}
									{{-- edit button --}}
									<a class="btn btn-info btn-block" href="{{route('si_resource.edit',['si_resource'=>$resource->id])}}">Edit Item</a>

									{{-- delete button --}}
									<form method="POST"class="my-2" action="{{route('si_resource.destroy',['si_resource' => $resource->id])}}">
										@csrf
										@method('DELETE')
										<button class="btn btn-warning btn-block">Delete Resource</button>
									</form>
									{{-- @endcan --}}
								</div>
							@endcan


						</div>

					</div>

				</div>

			</section>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				@cannot('isAdmin')
					<button class="btn btn-primary" type="submit" form="checkboxForm">Request</button>
				@endcannot
			</div>
		</div>
	</div>
</div> {{-- end modal --}}

@endforeach


@endsection

resources/views/SI_resources/show.blade.php
@extends('layouts.app')

@section('content')

<section class="container">
	<div class="row">

		<div class="col-12 col-md-8 mx-auto">
			@if (Session::has('update_success'))
				<div class="alert alert-success">
					{{Session::get('update_success')}}
				</div>
			@endif	


			<div class="card">
				<img src="{{url('/public/'.$si_resource->images)}}" class="card-img-top">
				<div class="card-body">

					<h2 class="card-title">{{$si_resource->name}}</h2>
					<p class="card-text">
						<strong>No. of Stocks: </strong>{{$si_resource->stocks}}
					</p>
					<p class="card-text">
						<strong>Details: </strong>{{$si_resource->details}}
					</p>
				</div>
				<div class="card-footer">

					{{-- view button --}}
					<a href="{{route('si_resource.index')}}" class="btn btn-primary btn-block">View All Resource</a>

					{{-- @can('isAdmin') --}}
					{{-- edit button --}}
					<a class="btn btn-info btn-block" href="{{route('si_resource.edit',['si_resource'=>$si_resource->id])}}">Edit Item</a>

					{{-- delete button --}}
					<form method="POST"class="my-2" action="{{route('si_resource.destroy',['si_resource' => $si_resource->id])}}">
						@csrf
						@method('DELETE')
						<button class="btn btn-warning btn-block">Delete Resource</button>
					</form>
					{{-- @endcan --}}
				</div>


			</div>

		</div>

	</div>

</section>

@endsection